
matrix:
  include:
    - language: node_js
      name: Bouncer Worker linter check
      dist: noble
      node_js:
        - "22.14.0"
      script:
        - cd tools/bouncer_worker && yarn install && yarn lint

      git:
        submodules: false

    - language: cpp
      dist: noble
      name: license support compilation check
      node_js:
        - "22.14.0"
      compiler:
           - gcc

      addons:
          apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc
                  - g++
      git:
          submodules: false

      before_install:
          - echo -e "machine github.com\n  login $TESTUSER\n  password $TESTPW" >~/.netrc
          - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          - sudo apt update
          - git submodule update --init --recursive
          - export BOUNCER_DIR=$PWD
          - mkdir testData && cd testData
          - git clone --filter=blob:none --sparse https://$TESTUSER:$TESTPW@github.com/3drepo/tests.git .
          - git sparse-checkout add cplusplus/bouncer/ext_libs/focal
          - git sparse-checkout add cplusplus/bouncer/ext_libs/noble
          - mv cplusplus/bouncer/ext_libs/focal/ .
          - mv cplusplus/bouncer/ext_libs/noble/ .
          - cd ../
          - echo ============ BOOST  INSTALL =============
          - sudo apt-get install libboost-all-dev
          - echo ============ MONGO  INSTALL =============
          - tar -zxf testData/noble/mongo-cxx-driver.tgz
          - export MONGO_ROOT=$PWD/mongo-cxx-driver
          - echo ============ ASSIMP INSTALL =============
          - tar -zxf testData/noble/assimp-5.4.3.tgz
          - export ASSIMP_ROOT=$PWD/assimp
          - echo ============ IFCOPENSHELL INSTALL =============
          - tar -zxf testData/noble/IfcOpenShell-0.8.0.tgz
          - sudo apt-get install tk-dev tcl-dev libxmu-dev libxi-dev libboost-all-dev libcgal-dev libocct-data-exchange-dev libocct-draw-dev libocct-foundation-dev libocct-modeling-algorithms-dev libocct-modeling-data-dev libocct-ocaf-dev libocct-visualization-dev libgmp-dev libmpfr-dev libxml2-dev libeigen3-dev
          - export IFCOPENSHELL_ROOT=$PWD/IfcOpenShell
          - echo ============ TEIGHA INSTALL =============
          - cat testData/focal/teigha/2026.9/teighaLinuxGCC8.3.tgz* | tar -zxf -
          - export ODA_ROOT=$PWD/teighaLinuxGCC8.3
          - export ODA_LIB_DIR=$ODA_ROOT/lib/lnxX64_8.3dll/
          - echo ============ SYNCHRO INSTALL =============
          - sudo apt-get install zlib1g-dev libssl-dev libxft-dev
          - tar -zxf testData/noble/thrift-0.12.0.tgz
          - tar -zxf testData/noble/3drepoSynchroReader.tgz
          - tar -zxf testData/focal/date.tgz
          - export THRIFT_ROOT=$PWD/thrift-0.12.0
          - export DATE_ROOT=$PWD/date
          - export SYNCHRO_READER_ROOT=$PWD/3drepoSynchroReader
          - echo ============ CRYPTOLENS INSTALL =============
          - sudo apt-get install libcurl4-openssl-dev
          - tar -zxf testData/noble/cryptoLens.tgz
          - export CRYPTOLENS_ROOT=$PWD/cryptoLens
            # dummy values just to ensure it compiles
          - export LICENSE_RSA_PUB_KEY_MOD="1bc"
          - export LICENSE_RSA_PUB_KEY_EXP="1bc"
          - export LICENSE_AUTH_TOKEN="1bc"
          - export LICENSE_PRODUCT_ID=123

      before_script:
          - mkdir build && cd build
      script:
            # check compilation with license enabled
          - cd $BOUNCER_DIR/build && cmake -DREPO_BUILD_TOOLS=ON -DREPO_BUILD_CLIENT=ON -DCMAKE_BUILD_TYPE=Release -DLICENSE_CHECK=ON -DCMAKE_INSTALL_PREFIX=$HOME/bouncer_install ../
          - sudo make install -j8

notifications:
    email:
        recipients:
            - 3drepo-devops@asite.com
