name: Build Docker Image (CI)

on:
  pull_request:
    branches:
      - master
      - staging

permissions: {}

jobs:
  build-docker:
    uses: ./.github/workflows/docker-build.yml
    with:
      target: init
