name: Run Docker build test

on:
  push:
    tags-ignore:
      - '*'

permissions:
  contents: read

jobs:
  build-docker:
    uses: ./.github/workflows/_dockerBuild.yml
    with:
      target: init
